### PR TITLE
Paint callbacks

### PR DESCRIPTION
**Pull request by Past9**
I took a stab at implementing paint callbacks. Rendering is a bit outside my normal wheelhouse so I'm not sure if this is the best approach, but I'm happy to make adjustments.

```
cargo run --example triangle
```

### CODE REVIEW

**Comment by hakolao** [comment]
Thanks! I’ll try to get a look at this tomorrow

**Review by hakolao — CHANGES_REQUESTED** [review]
Looks good to me, thanks for implementing this.

Can you run `cargo clippy` on it, and fix those warnings. And perhaps rename the `triangle` example to `paint_callback`? 

Lastly, add the new example to the simple `run_all_examples` script.

Sorry for taking longer, I got distracted by new years :)

**Comment by Past9** [comment]
Thanks for the review! Made those changes.

**Comment by hakolao** [comment]
Looks like the clippy still failed @Past9, might be that you were running it on old rust version. Do `rustup update` and fix the error, then retry?

**Comment by Past9** [comment]
I made the fix that the workflow log is asking for.

Unfortunately I can't run `clippy` on nightly at the moment due to a compiler bug when building `vulkano-shaders` on Windows, and I don't have a linux installation at the moment. But hopefully this fix will satisfy clippy.

**Comment by Past9** [comment]
The last run failed to download python on both Windows and Linux. I'm assuming this is just an intermittent thing and would probably succeed on another run? I don't see anything in my PR that should cause that issue.

**Comment by hakolao** [comment]
I’ll try to figure out the CI later today.

**Pull request merged**
