### PR TITLE
Updated egui to 0.23.

### PR DESCRIPTION
**Pull request by Letronix624**

### CODE REVIEW

**Comment by hakolao** [comment]
Amazing, remember to run the `cargo fmt` with nightly: `cargo +nightly fmt`, because I use some formatting rules that only work there. (`rustfmt.toml`).

**Review by hakolao — CHANGES_REQUESTED** [review]
Thanks for this! :)

Examples run fine, but I noticed that the color test (blending) in the demo app differ from the older version. You can see some lines within the color images.

New:
image

Old:
image

On a quick glance I can't see a change that would cause this. But perhaps you might. Can be worth testing if it comes from the egui update also.

~~Also, run the `cargo +nightly fmt` to properly format :)~~ you did :)

**Comment by Letronix624** [comment]
I found the reason! (After some long time just going through my changes)
As you suspected the problem originates from the newest version of either Egui or it's demo crate.
What should we do? Keep the version of Egui on 0.22 or accept living with the 0.23 problem?

**Comment by hakolao** [comment]
Maybe accept living with it then.

**Comment by hakolao** [comment]
Hey, apologies. #50 just went through with lints etc. I was hoping if you could update this PR to just update the egui library? Then we can make a new release

**Comment by aedm** [comment]
> Hey, apologies. #50 just went through with lints etc. I was hoping if you could update this PR to just update the egui library? Then we can make a new release

My bad, I totally missed this PR when I started mine. :( Sorry!

**Comment by Letronix624** [comment]
oops. I forgot about the lints because I don't have them set up the same way.

 I'm going to do that later today.

**Comment by hakolao** [comment]
> oops. I forgot about the lints because I don't have them set up the same way.
> 
> I'm going to do that later today.

No rush!

**Comment by Letronix624** [comment]
oops

**Pull request merged**
