### PR TITLE
Allow sRGB and non-sRGB target surfaces to be used

### PR DESCRIPTION
**Pull request by alnyan**
I managed to get both sRGB and non-sRGB output formats working consistently. I also added (breaking change) an option to provide the specific format the surface was created with, if it's not default, otherwise format check would panic.

### CODE REVIEW

**Comment by alnyan** [comment]
As for my choice of uniform buffer for providing conversion options: sadly, vulkano docs say GLSL -> SPIR-V compiler does not support multiple entry points at the moment, so we have to control that at shader run-time via this uniform buffer. I made it immutable so performance hit should be negligible.

**Comment by hakolao** [comment]
I think I’d prefer push constant rather than the uniform buffer (afaik vulkan recommends using those). Just add one next to the screen size. Then the perf hit is zero.

I’ll check the rest a bit later :)

**Review by hakolao — COMMENTED** [review]
This seems to break the gradients.

What is (this PR):

image

Should be (master):

image

It works correctly when using `Format::R8G8B8A8_SRGB` for the font image. And doing the color conversion in the **vertex shader**. However, then we're in the same situation as the current `master` branch is. So as far as I undestand, when using `UNORM` for the swapchain images, we should then do some other kind of conversion to get the same results.

I'm kind of thinking that the default should be `SRGB` (based on the top answer and his links [here](https://stackoverflow.com/questions/66401081/vulkan-swapchain-format-unorm-vs-srgb)) and then if one wants to use `UNORM` swapchain images, they can set the format to `UNORM`. But in that case, the font image should also be `UNORM`, unless you can figure out the conversion in the shaders.

If I am understanding this correctly. The egui pixels are in `SRGB` color space. Most devices color space is `SrgbNonLinear`. And if swapchain image format is SRGB, gpu will convert the linear to `SRGB` (good). So that's why we need to convert our only vertex colors to linear in the shaders, the image already is in the right color space.

But if swapchain image is UNORM, gpu will not convert it, but it will still be interpreted as `SRGB`. So the fragment shader needs to do a bit more converting in that case.

So actually the texture color conversions need to take place only in the case of `NumericType::UNORM`.

**Comment by hakolao** [comment]
I pushed two commits to fix the `UNORM` case (similar to [egui_glium](https://github.com/emilk/egui/blob/master/egui_glium/src/shader/fragment_300es.glsl)), and also added a second window to `demo_app` to compare the colors. Now they are almost the same. Not quite, but almost.

After doing research, I am inclined to say that using `SRGB` format for swapchain images is preferred...

Left SRGB for swapchain image, right UNORM for swapchain image

image

**Comment by alnyan** [comment]
I think we may leave both sRGB and non-sRGB output formats to be available, but add an explicit notice that sRGB should be preferred over plain RGB. I'll try some more fixes to that, but I'm not sure what else I can do at this point

**Comment by hakolao** [comment]
~~Want to add it so that we select srgb when None is provided? :)~~ Did that.

Let me know if there's any more changes you intend to do. This looks good to me now

**Comment by alnyan** [comment]
Looks good to me as well, sorry for late reply

**Comment by hakolao** [comment]
Thanks for help @alnyan !

**Pull request merged**
