### PR TITLE
Fix color space

### PR DESCRIPTION
**Pull request by hakolao**
Use `B8G8R8A8_SRGB` for the image format. This should give the right color outputs

### CODE REVIEW

**Comment by hakolao** [comment]
@alnyan  Want to try with this branch? For the srgb changes. Swapchain should be created with `B8G8R8A8_SRGB`

**Comment by hakolao** [comment]
Though now the textures should also be SRGB

**Comment by alnyan** [comment]
The change looks good — sRGB surface rendering works fine. I'm not sure forcing one specific surface format to be used is a good idea, though, but I'm okay with that

**Comment by hakolao** [comment]
I wasn't sure about that either. However, when researching into it it seems that SRGB is preferred for images. Thus I think it is better for this library, and should be available on all devices. I would not mind using the UNORM or have it be configurable, but I have not been able to get the colors fully correspond the egui color test with other than SRGB.

I am using this in my projects and the only downside seems to be that I gotta do the linear to srgb conversion when using Storage images in my compute shaders with UNORM (srgb seems to not be allowed for storage usage).

**Comment by alnyan** [comment]
I managed to get consistent colors with either sRGB/non-sRGB output formats, but it conflicts with the latest patch, so I'll prepare a new PR, if you're okay with that

**Comment by hakolao** [comment]
I am! Check also the color test against egui web with the demo app example. Gradients seemed to be the difficult ones.

**Pull request merged**
